version: '3'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - data-volume:/data

  scraper:
    build: ./scraper
    volumes:
      - data-volume:/data

volumes:
  data-volume:
